# Generated by Django 2.0.7 on 2018-07-24 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(null=True, verbose_name='Sposób przyrządzenia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Zdjęcie produktu')),
                ('preparation_time', models.CharField(choices=[('very_fast', 'poniżej 15 minut'), ('fast', '15 - 30 minut'), ('medium', '30 - 60 minut'), ('long', 'powyżej 60 minut')], default='fast', max_length=50, verbose_name='Czas przygotowania')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Treść')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(related_name='meals', to='meals.MealCategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='comments',
            field=models.ManyToManyField(related_name='meals', to='meals.MealComment'),
        ),
    ]
