# Generated by Django 2.0.7 on 2018-07-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180725_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10, null=True),
        ),
    ]
