# Generated by Django 2.0.7 on 2018-07-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
