# Generated by Django 2.0.7 on 2018-07-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.CharField(max_length=10000, null=True, verbose_name='Content'),
        ),
    ]
